import { DEFAULT_CODING_ROLES } from '../../../shared/constants';
import type { WorkflowGraph } from './types';

export const codingGraph: WorkflowGraph = {
  schemaVersion: 1,
  id: 'coding',
  mode: 'coding',
  start: 'plannerSpec',
  roles: {
    planner: { defaultProvider: DEFAULT_CODING_ROLES.planner, uiLabel: 'Planner', runtimeLabel: '規劃師' },
    reviewer: { defaultProvider: DEFAULT_CODING_ROLES.reviewer, uiLabel: 'Reviewer', runtimeLabel: '審查者' },
    coder: { defaultProvider: DEFAULT_CODING_ROLES.coder, uiLabel: 'Coder', runtimeLabel: 'Coder' },
    tester: { defaultProvider: DEFAULT_CODING_ROLES.tester, uiLabel: 'Tester', runtimeLabel: 'Tester' },
  },
  preflight: { kind: 'serial', requiredRoles: ['planner', 'reviewer', 'coder', 'tester'] },
  nodes: {
    plannerSpec: {
      kind: 'step',
      provider: { type: 'role', role: 'planner' },
      role: 'planner',
      label: '規劃師',
      status: { builder: 'status.coding.plannerSpec' },
      prompt: { builder: 'coding.plannerSpec', args: [{ kind: 'input', name: 'question' }] },
      output: 'spec',
      policy: 'serialRunStep',
    },
    reviewerSpec: {
      kind: 'step',
      provider: { type: 'role', role: 'reviewer' },
      role: 'reviewer',
      label: '審查者',
      status: { builder: 'status.coding.reviewerSpec' },
      prompt: {
        builder: 'coding.reviewerSpec',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'plannerSpec' },
          { kind: 'providerName', provider: { type: 'role', role: 'planner' } },
        ],
      },
      output: 'specReview',
      policy: 'serialRunStep',
    },
    coderV1: {
      kind: 'step',
      provider: { type: 'role', role: 'coder' },
      role: 'coder',
      label: 'Coder',
      status: { builder: 'status.coding.coderV1' },
      prompt: {
        builder: 'coding.coderV1',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'plannerSpec' },
          { kind: 'providerName', provider: { type: 'role', role: 'planner' } },
          { kind: 'output', node: 'reviewerSpec' },
          { kind: 'providerName', provider: { type: 'role', role: 'reviewer' } },
        ],
      },
      output: 'codeV1',
      policy: 'serialRunStep',
    },
    reviewerCode: {
      kind: 'step',
      provider: { type: 'role', role: 'reviewer' },
      role: 'reviewer',
      label: 'Code Review',
      status: { builder: 'status.coding.reviewerCode' },
      prompt: {
        builder: 'coding.reviewerCode',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'coderV1' },
          { kind: 'providerName', provider: { type: 'role', role: 'coder' } },
        ],
      },
      output: 'codeReview',
      policy: 'serialRunStep',
    },
    testerCases: {
      kind: 'step',
      provider: { type: 'role', role: 'tester' },
      role: 'tester',
      label: 'Tester',
      status: { builder: 'status.coding.testerCases' },
      prompt: {
        builder: 'coding.testerCases',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'coderV1' },
          { kind: 'providerName', provider: { type: 'role', role: 'coder' } },
        ],
      },
      output: 'testReport',
      policy: 'serialRunStep',
    },
    coderV2: {
      kind: 'step',
      provider: { type: 'role', role: 'coder' },
      role: 'coder',
      label: 'v2 修正',
      status: { builder: 'status.coding.coderV2' },
      prompt: {
        builder: 'coding.coderV2',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'coderV1' },
          { kind: 'output', node: 'reviewerCode' },
          { kind: 'providerName', provider: { type: 'role', role: 'reviewer' } },
          { kind: 'output', node: 'testerCases' },
          { kind: 'providerName', provider: { type: 'role', role: 'tester' } },
        ],
      },
      output: 'codeV2',
      policy: 'serialRunStep',
    },
    plannerAcceptance: {
      kind: 'step',
      provider: { type: 'role', role: 'planner' },
      role: 'planner',
      label: '驗收',
      status: { builder: 'status.coding.plannerAcceptance' },
      prompt: {
        builder: 'coding.plannerAcceptance',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'coderV2' },
          { kind: 'providerName', provider: { type: 'role', role: 'coder' } },
          { kind: 'output', node: 'plannerSpec' },
        ],
      },
      output: 'acceptance',
      policy: 'serialRunStep',
    },
    coderFinal: {
      kind: 'step',
      provider: { type: 'role', role: 'coder' },
      role: 'coder',
      label: '最終版',
      status: { builder: 'status.coding.coderFinal' },
      prompt: {
        builder: 'coding.coderFinal',
        args: [
          { kind: 'input', name: 'question' },
          { kind: 'output', node: 'coderV2' },
          { kind: 'output', node: 'plannerAcceptance' },
          { kind: 'providerName', provider: { type: 'role', role: 'planner' } },
        ],
      },
      output: 'finalCode',
      policy: 'serialRunStep',
    },
  },
  edges: [
    { from: 'plannerSpec', to: 'reviewerSpec' },
    { from: 'reviewerSpec', to: 'coderV1' },
    { from: 'coderV1', to: 'reviewerCode' },
    { from: 'reviewerCode', to: 'testerCases' },
    { from: 'testerCases', to: 'coderV2' },
    { from: 'coderV2', to: 'plannerAcceptance' },
    { from: 'plannerAcceptance', to: 'coderFinal' },
  ],
  onComplete: { status: '' },
};
